### ISSUE TITLE
Starrybound automatically reset gamePort to 21025

### ISSUE THREAD

**Issue by Retalyx** [AvilanceLtd/StarryboundServer#37] opened 2013-12-31 08:08 UTC
When i launch Starrybound, it regenerate a new starbound.config file with gamePort set to 21025

starbound.config: http://screens.retalyx.fr/20131231080345501.png
starrybound/config.json: http://screens.retalyx.fr/20131231080654775.png

Because of that i can't connect to my server because my client directly connect to the server, without the Starrybound proxy.

**Comment by saybrook** [comment] 2013-12-31 13:48
i had this issue in a previous build but the latest master 1.2.1.1 should no longer do this?

**Comment by Retalyx** [comment] 2013-12-31 14:55
I'm on 1.2.1.1

**Comment by saybrook** [comment] 2013-12-31 15:07
interesting.  im not having this issue now.  even when you delete starbound.config and let starrybound recreate it this still happens?

**Comment by Retalyx** [comment] 2013-12-31 16:03
Yes :( I tried:
Changing gamePort to something else like 22125 -> After launching gamePort: 21025
Removing starbound.config -> After launching gamePort: 21025
Revoke write permissions on starbound.config (to disallow overwritting of gamePort)-> Crash on launching :/

**Comment by Crashdoom** [comment] 2013-12-31 19:30
The proxy does reset the port to 21025 on the local starbound.config upon start so that any clients connecting from the same computer are able to connect via the proxy instead of via the server. However, the port the parent server starts from will be what you've set in the config.json (22125).

What seems to be the issue you're having?

**Comment by Retalyx** [comment] 2014-01-01 00:12
The problem is, because the gamePort is automatically reset to 21025, when i connect from another computer than the server, it said wrong password because it connected to the server, not the proxy... So the only way i found to get clients to connect on the proxy and not to the server is to change the proxyPort to something else like 21005, and connect to the server via ipaddress:21005 because i can't use the default port :(

The server is installed on a ubuntu server x64 13.04 running mono Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-5ubuntu1)

The client is installed on a Windows 7 Ultimate x64

**Comment by Crashdoom** [comment] 2014-01-02 20:55
@Retalyx I'm unable to reproduce this error, the gameport should be reset to 21025 automatically by the Starrybound server however it will use the server port specified in your config.json. Are you able to send the log files relating to this issue to starrybound-dev@avilance.com?

**Comment by Retalyx** [comment] 2014-01-03 03:53
Mail sent ;)

**Comment by saybrook** [comment] 2014-01-03 13:14
#46 might be a dupe of this but the behavior is the same. to clarify, the game port in the starbound.config file cannot be 21025 as the starrybound proxy listens on this port.  Something (as of the current dev build reported in #46) is forcing the starbound.config game port value to 21025 result is clients cannot connect.

**Comment by Retalyx** [comment] 2014-01-03 13:21
Exactly
(Sorry if my english wasn't perfect to explain the issue, i'm french :s)

**Closed as completed** 2014-01-10 00:50 UTC
Labels: bug, unable to reproduce, requires information
