### ISSUE TITLE
UUID auth does not appear to be working

### ISSUE THREAD

**Issue by saybrook** [AvilanceLtd/StarryboundServer#42] opened 2014-01-01 16:46 UTC
I have deleted/recreated my  'darkos.json' in the players folder and set the group to superadmin and it does not recognize me as superadmin.

I let starrybound recreate the file while offline, then login, then log off, then change the group and login.. still doesn't work.

**Comment by saybrook** [comment] 2014-01-01 16:47
sorry this is with latest dev 1.2.1.19937

**Comment by Crashdoom** [comment] 2014-01-01 16:48
Duplicate of issue #41

**Closed as completed by Crashdoom** 2014-01-01 16:48 UTC
Labels: duplicate
